defaults: &defaults
    docker:
      - image: circleci/node:10
    working_directory: ~/courier

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-courier-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-courier-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-courier-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build React app
          command: yarn build
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -f ./.circleci/Dockerfile -t courier:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM .
      - persist_to_workspace:
          root: .
          paths:
            - ./build


workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
